refactored for issue#1
ArchanaVaideeswaran/crypto-airdrop pull request #2
Opened 2022-12-07 13:28 UTC by ArchanaVaideeswaran

2022-12-07 19:54 UTC, sumit03guha commented on hardhat.config.ts
> +                    evmVersion: "istanbul",
no need to mention the evmVersion explicitly. The default and the latest one is `london`

2022-12-07 19:55 UTC, sumit03guha requested changes
remove the `evmVersion` key from hardhat config file.

2022-12-08 04:45 UTC, ArchanaVaideeswaran commented on hardhat.config.ts
> +                },
removed evmVersion

2022-12-08 08:17 UTC, sumit03guha commented
LGTM

2022-12-08 08:21 UTC, merged